### ISSUE TITLE
Re-Planting Mangoes

### ISSUE THREAD

**Issue by hydrop0x** [anviaan/SimpleMango#2]
Is there a way to plant mango trees, if so, how?

**Comment by hydrop0x** [comment]
Never mind, I was being stupid, but how do I get a mango sapling?

**Comment by anviaan** [comment]
There is a bug in the leaves of the tree, they do not give what they should (mango sapling).
I am already solving it

**Comment by anviaan** [comment]
There is a bug in the leaves of the tree, they do not give what they should. 
I'm already solving it

**Comment by hydrop0x** [comment]
Okay, thanks

**Comment by anviaan** [comment]
Bug fixed
